# ==========================================
# HYPRLAND
# ==========================================
source = ~/.config/hypr/modules/env_variables.conf
source = ~/.config/hypr/modules/autostart.conf
source = ~/.config/hypr/modules/permissions.conf
source = ~/.config/hypr/modules/style.conf
source = ~/.config/hypr/modules/input.conf
source = ~/.config/hypr/modules/workspace.conf

# ==========================================
# DANK MATERIAL SHELL
# ==========================================
source = ./dms/colors.conf
source = ./dms/layout.conf
source = ./dms/binds.conf
source = ./dms/cursor.conf
source = ./dms/outputs.conf
source = ./dms/windowrules.conf
